/**
 * export.js — SQL & NoSQL Export Routes (WITH DATA)
 *
 * Now exports the full table: schema DDL + actual data rows.
 *
 *   GET /api/export/sql/:tableId?uid=              — SQL as JSON
 *   GET /api/export/sql/:tableId/download?uid=     — Download .sql
 *   GET /api/export/nosql/:tableId?uid=            — NoSQL JSON
 *   GET /api/export/nosql/:tableId/download?uid=   — Download .json
 */

import { Router } from 'express';
import pool from '../db.js';

const router = Router();

// ══════════════════════════════════════════════════════════════════════════════
// HELPER: Parse raw CSV string → { headers, rows }
// ══════════════════════════════════════════════════════════════════════════════
function parseCSV(rawContent) {
  if (!rawContent) return { headers: [], rows: [] };

  const lines = rawContent.trim().split('\n').filter(l => l.trim());
  if (lines.length < 1) return { headers: [], rows: [] };

  // Parse a single CSV line respecting double-quoted fields
  const parseLine = (line) => {
    const result = [];
    let cur = '';
    let inQuote = false;
    for (let i = 0; i < line.length; i++) {
      const ch = line[i];
      if (ch === '"') {
        inQuote = !inQuote;
      } else if (ch === ',' && !inQuote) {
        result.push(cur.trim());
        cur = '';
      } else {
        cur += ch;
      }
    }
    result.push(cur.trim());
    return result;
  };

  const headers = parseLine(lines[0]);
  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    if (!lines[i].trim()) continue;
    const values = parseLine(lines[i]);
    const row = {};
    headers.forEach((h, idx) => {
      row[h] = values[idx] !== undefined ? values[idx] : null;
    });
    rows.push(row);
  }

  return { headers, rows };
}

// ══════════════════════════════════════════════════════════════════════════════
// HELPER: Escape a value for SQL INSERT
// ══════════════════════════════════════════════════════════════════════════════
function sqlEscape(val) {
  if (val === null || val === undefined || val === '') return 'NULL';
  const str = String(val);
  // If it looks like a pure integer or decimal, don't quote it
  if (/^-?\d+$/.test(str))          return str;
  if (/^-?\d+\.\d+$/.test(str))     return str;
  // Escape backslashes and single quotes
  return `'${str.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

// ══════════════════════════════════════════════════════════════════════════════
// HELPER: Build SQL CREATE TABLE + INSERT INTO
// ══════════════════════════════════════════════════════════════════════════════
function buildSQL(tableName, attributes, rawContent) {
  // ── DDL ────────────────────────────────────────────────────────────────────
  const colLines = attributes.map(attr => {
    let line = `  \`${attr.column_name}\` ${attr.data_type}`;
    if (attr.is_nullable === 'NO') line += ' NOT NULL';
    if (attr.default_value)        line += ` DEFAULT ${attr.default_value}`;
    return line;
  });

  const tableConstraints = [];

  // Primary key
  const pkCol = attributes.find(a => a.is_primary === 'YES');
  if (pkCol) tableConstraints.push(`  PRIMARY KEY (\`${pkCol.column_name}\`)`);

  // Unique keys
  for (const a of attributes) {
    if (a.constraints?.toUpperCase().includes('UNIQUE')) {
      tableConstraints.push(`  UNIQUE KEY \`uq_${a.column_name}\` (\`${a.column_name}\`)`);
    }
  }

  // Check constraints
  for (const a of attributes) {
    if (a.constraints) {
      const m = a.constraints.match(/CHECK\s*\(([^)]*)\)/i);
      if (m) tableConstraints.push(`  CONSTRAINT \`chk_${tableName}_${a.column_name}\` ${m[0]}`);
    }
  }

  // Foreign keys
  for (const a of attributes) {
    if (a.is_foreign === 'YES' && a.foreign_ref) {
      const parts = a.foreign_ref.split('.');
      if (parts.length === 2) {
        const [refTable, refCol] = parts;
        tableConstraints.push(
          `  CONSTRAINT \`fk_${tableName}_${a.column_name}\`\n` +
          `    FOREIGN KEY (\`${a.column_name}\`)\n` +
          `    REFERENCES \`${refTable}\`(\`${refCol}\`)\n` +
          `    ON DELETE CASCADE ON UPDATE CASCADE`
        );
      }
    }
  }

  const ddl =
    `-- Generated by DATA MORPH\n` +
    `-- Table: ${tableName}\n` +
    `-- Exported: ${new Date().toISOString()}\n\n` +
    `CREATE TABLE IF NOT EXISTS \`${tableName}\` (\n` +
    [...colLines, ...tableConstraints].join(',\n') +
    `\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n`;

  // ── INSERT INTO (with actual data) ────────────────────────────────────────
  const { headers, rows } = parseCSV(rawContent);

  if (rows.length === 0) {
    return ddl + '\n-- No data rows found.\n';
  }

  // Only use the columns that actually exist in dm_attributes
  const attrNames = attributes.map(a => a.column_name);
  const usedHeaders = headers.filter(h => attrNames.includes(h));

  if (usedHeaders.length === 0) {
    return ddl + '\n-- Column mismatch: no matching columns found in CSV.\n';
  }

  const colList = usedHeaders.map(h => `\`${h}\``).join(', ');

  // Chunk inserts in groups of 500 for readability
  const CHUNK = 500;
  const insertBlocks = [];
  for (let i = 0; i < rows.length; i += CHUNK) {
    const chunk = rows.slice(i, i + CHUNK);
    const valueRows = chunk.map(row => {
      const vals = usedHeaders.map(h => sqlEscape(row[h]));
      return `  (${vals.join(', ')})`;
    });
    insertBlocks.push(
      `INSERT INTO \`${tableName}\` (${colList}) VALUES\n${valueRows.join(',\n')};\n`
    );
  }

  return ddl + '\n' + insertBlocks.join('\n');
}

// ══════════════════════════════════════════════════════════════════════════════
// HELPER: Build NoSQL — actual JSON documents array
// ══════════════════════════════════════════════════════════════════════════════
function buildNoSQL(tableName, attributes, rawContent) {
  const { headers, rows } = parseCSV(rawContent);

  // Type coerce values based on dm_attributes data_type
  const typeMap = {};
  for (const a of attributes) {
    const t = (a.data_type || '').toUpperCase();
    if (t.startsWith('INT') || t === 'BIGINT' || t === 'SMALLINT' || t === 'TINYINT') {
      typeMap[a.column_name] = 'int';
    } else if (t.startsWith('DECIMAL') || t.startsWith('FLOAT') || t.startsWith('DOUBLE')) {
      typeMap[a.column_name] = 'float';
    } else if (t === 'BOOLEAN' || t === 'BOOL' || t === 'TINYINT(1)') {
      typeMap[a.column_name] = 'bool';
    } else {
      typeMap[a.column_name] = 'string';
    }
  }

  const coerce = (val, type) => {
    if (val === null || val === undefined || val === '') return null;
    if (type === 'int')   return parseInt(val,   10) || 0;
    if (type === 'float') return parseFloat(val)     || 0.0;
    if (type === 'bool')  return val === 'true' || val === '1' || val === 'yes';
    return val;
  };

  const docs = rows.map(row => {
    const doc = {};
    for (const h of headers) {
      if (typeMap[h] !== undefined) {
        doc[h] = coerce(row[h], typeMap[h]);
      } else {
        doc[h] = row[h];
      }
    }
    return doc;
  });

  // Build the Mongoose schema definition too (for reference)
  const schemaFields = {};
  for (const a of attributes) {
    const t = typeMap[a.column_name] || 'string';
    const mongoType = t === 'int' || t === 'float' ? 'Number'
      : t === 'bool' ? 'Boolean' : 'String';
    const def = { type: mongoType, required: a.is_nullable === 'NO' };
    if (a.is_primary === 'YES' || a.constraints?.toUpperCase().includes('UNIQUE')) def.unique = true;
    if (a.default_value) def.default = a.default_value;
    schemaFields[a.column_name] = def;
  }

  const schemaJSON = JSON.stringify(schemaFields, null, 2)
    .replace(/"Number"/g, 'Number')
    .replace(/"Boolean"/g, 'Boolean')
    .replace(/"String"/g, 'String')
    .replace(/"Date"/g, 'Date');

  const mongooseCode =
    `const mongoose = require('mongoose');\n\n` +
    `const ${tableName}Schema = new mongoose.Schema(\n${schemaJSON},\n` +
    `  { timestamps: true }\n);\n\n` +
    `module.exports = mongoose.model('${tableName}', ${tableName}Schema);\n`;

  const indexes = attributes
    .filter(a => a.is_primary === 'YES' || a.constraints?.toUpperCase().includes('UNIQUE'))
    .map(a => `db.${tableName}.createIndex({ ${a.column_name}: 1 }, { unique: true });`);

  return {
    collectionName: tableName,
    documents:      docs,
    documentCount:  docs.length,
    mongooseCode,
    indexes,
  };
}

// ══════════════════════════════════════════════════════════════════════════════
// HELPER: Fetch table + attributes + raw CSV
// ══════════════════════════════════════════════════════════════════════════════
async function getTableAndAttrs(tableId, uid) {
  const [tables] = await pool.execute(
    `SELECT tm.*, di.raw_content
       FROM dm_table_master tm
       LEFT JOIN dm_input_data di ON di.data_id = tm.data_id
      WHERE tm.table_id = ? AND tm.user_uid = ?`,
    [tableId, uid]
  );
  if (!tables.length) throw { code: 404, message: 'Table not found.' };

  const [attrs] = await pool.execute(
    'SELECT * FROM dm_attributes WHERE table_id = ? ORDER BY attr_id ASC',
    [tableId]
  );
  if (!attrs.length) throw { code: 400, message: 'No columns found. Please complete the schema builder first.' };

  return {
    table:      tables[0],
    attrs,
    rawContent: tables[0].raw_content || '',
  };
}

// ══════════════════════════════════════════════════════════════════════════════
// GET /api/export/sql/:tableId?uid=
// ══════════════════════════════════════════════════════════════════════════════
router.get('/sql/:tableId', async (req, res) => {
  const { tableId } = req.params;
  const { uid }     = req.query;
  if (!uid) return res.status(400).json({ error: 'uid is required.' });

  try {
    const { table, attrs, rawContent } = await getTableAndAttrs(tableId, uid);
    const sql = buildSQL(table.table_name, attrs, rawContent);
    const { rows } = parseCSV(rawContent);

    pool.execute(
      'INSERT INTO dm_exports (table_id, user_uid, export_type) VALUES (?, ?, "SQL")',
      [tableId, uid]
    ).catch(() => {});

    res.json({ tableName: table.table_name, exportType: 'SQL', sql, rowCount: rows.length, columnCount: attrs.length });
  } catch (err) {
    if (err.code) return res.status(err.code).json({ error: err.message });
    console.error('[Export/SQL Error]', err);
    res.status(500).json({ error: 'Failed to generate SQL.', details: err.message });
  }
});

// ══════════════════════════════════════════════════════════════════════════════
// GET /api/export/sql/:tableId/download?uid=
// ══════════════════════════════════════════════════════════════════════════════
router.get('/sql/:tableId/download', async (req, res) => {
  const { tableId } = req.params;
  const { uid }     = req.query;
  if (!uid) return res.status(400).json({ error: 'uid is required.' });

  try {
    const { table, attrs, rawContent } = await getTableAndAttrs(tableId, uid);
    const sql = buildSQL(table.table_name, attrs, rawContent);

    pool.execute(
      'INSERT INTO dm_exports (table_id, user_uid, export_type) VALUES (?, ?, "SQL")',
      [tableId, uid]
    ).catch(() => {});

    res.setHeader('Content-Type',        'text/plain; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${table.table_name}.sql"`);
    res.send(sql);
  } catch (err) {
    if (err.code) return res.status(err.code).json({ error: err.message });
    console.error('[Export/SQL/download Error]', err);
    res.status(500).json({ error: 'Failed to download SQL.' });
  }
});

// ══════════════════════════════════════════════════════════════════════════════
// GET /api/export/nosql/:tableId?uid=
// ══════════════════════════════════════════════════════════════════════════════
router.get('/nosql/:tableId', async (req, res) => {
  const { tableId } = req.params;
  const { uid }     = req.query;
  if (!uid) return res.status(400).json({ error: 'uid is required.' });

  try {
    const { table, attrs, rawContent } = await getTableAndAttrs(tableId, uid);
    const nosql = buildNoSQL(table.table_name, attrs, rawContent);

    pool.execute(
      'INSERT INTO dm_exports (table_id, user_uid, export_type) VALUES (?, ?, "NoSQL")',
      [tableId, uid]
    ).catch(() => {});

    res.json({ tableName: table.table_name, exportType: 'NoSQL', ...nosql });
  } catch (err) {
    if (err.code) return res.status(err.code).json({ error: err.message });
    console.error('[Export/NoSQL Error]', err);
    res.status(500).json({ error: 'Failed to generate NoSQL.', details: err.message });
  }
});

// ══════════════════════════════════════════════════════════════════════════════
// GET /api/export/nosql/:tableId/download?uid=   → downloads .json (real docs)
// ══════════════════════════════════════════════════════════════════════════════
router.get('/nosql/:tableId/download', async (req, res) => {
  const { tableId } = req.params;
  const { uid }     = req.query;
  if (!uid) return res.status(400).json({ error: 'uid is required.' });

  try {
    const { table, attrs, rawContent } = await getTableAndAttrs(tableId, uid);
    const nosql = buildNoSQL(table.table_name, attrs, rawContent);

    const header =
      `// Generated by DATA MORPH\n` +
      `// Collection: ${table.table_name}\n` +
      `// Documents:  ${nosql.documentCount}\n` +
      `// Exported:   ${new Date().toISOString()}\n\n`;

    // Export as a proper JSON array the user can import into mongo:
    // mongoimport --jsonArray --file employees.json --collection employees
    const jsonContent =
      header +
      `// === MONGOOSE MODEL ===\n` +
      nosql.mongooseCode + '\n' +
      (nosql.indexes.length ? `// Indexes:\n${nosql.indexes.join('\n')}\n\n` : '') +
      `// === DATA (${nosql.documentCount} documents) ===\n` +
      `// Copy the JSON below and use: mongoimport --jsonArray\n` +
      JSON.stringify(nosql.documents, null, 2) + '\n';

    pool.execute(
      'INSERT INTO dm_exports (table_id, user_uid, export_type) VALUES (?, ?, "NoSQL")',
      [tableId, uid]
    ).catch(() => {});

    res.setHeader('Content-Type',        'text/plain; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="${table.table_name}.nosql.js"`);
    res.send(jsonContent);
  } catch (err) {
    if (err.code) return res.status(err.code).json({ error: err.message });
    console.error('[Export/NoSQL/download Error]', err);
    res.status(500).json({ error: 'Failed to download NoSQL export.' });
  }
});

export default router;
